/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.workload.thriftGeneratedClasses;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2022-10-25")
public enum QueryDataType implements org.apache.thrift.TEnum {
  TRAINING_DATA(0),
  TESTING_DATA(1);

  private final int value;

  private QueryDataType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static QueryDataType findByValue(int value) { 
    switch (value) {
      case 0:
        return TRAINING_DATA;
      case 1:
        return TESTING_DATA;
      default:
        return null;
    }
  }
}
