/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.workload.thriftGeneratedClasses;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2022-10-25")
public enum WorkLoadMetric implements org.apache.thrift.TEnum {
  CPU(0),
  NETWORK_IN(1),
  NETWORK_OUT(2),
  MEMORY(3),
  FINAL_TARGET(4);

  private final int value;

  private WorkLoadMetric(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static WorkLoadMetric findByValue(int value) { 
    switch (value) {
      case 0:
        return CPU;
      case 1:
        return NETWORK_IN;
      case 2:
        return NETWORK_OUT;
      case 3:
        return MEMORY;
      case 4:
        return FINAL_TARGET;
      default:
        return null;
    }
  }
}
